replicaCount: 4

image:
  repository: ravikiiran/hello-world
  tag: 5.0
  pullPolicy: Always

service:
  type: NodePort
  port: 8081
  targetPort: 8080
  nodePort: 30081

containerPort: 8080

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1
